#!/bin/sh

#+
#  Name:
#     startab

#  Purpose:
#     Redirects the user to TOPCAT

#  Description:
#     This shell script used to invoke the table viewer application.
#     Now it tells the user to do it under a different name.

#  Authors:
#     MBT: Mark Taylor (Starlink)
#-

echo "The 'startab' script no longer works."
echo "Please use the invocation 'topcat'."
