#!/bin/sh

#+
#  Name:
#     tablecopy

#  Purpose:
#     Standin for obsolete tablecopy script.

#  Description:
#     This shell script explains why it is going to refuse to 
#     invoke the TableCopy application.

#  Authors:
#     MBT: Mark Taylor (Starlink)
#-

cat <<__EOT__

   The tablecopy command is deprecated.
   If you want to replicate its behaviour, you can run

      java -classpath java/lib/table/table.jar uk.ac.starlink.table.TableCopy 

   However, you'd be better off using the tcopy or tpipe commands of
   the STILTS package, which are both more efficient and more capable.
   See

      http://www.starlink.ac.uk/stilts/

   This script may disappear altogether in future releases.

__EOT__
