
opts = [
   ['B', 'B', 'Rc'],
   ['H2', 'H2', 'Ks2'],
   ['H2', 'J2', 'H2'],
   ['H', 'H', 'K'],
   ['H', 'J', 'H'],
   ['Ic', 'V', 'Ic' ],
   ['J2', 'J2', 'Ks2'],
   ['J2', 'J2', 'H2'],
   ['J', 'J', 'K'],
   ['J', 'J', 'H'],
   ['Ks2', 'J2', 'Ks2'],
   ['Ks2', 'H2', 'Ks2'],
   ['K', 'H', 'K'],
   ['Rc', 'B', 'Rc'],
   ['U', 'U', 'Rc'],
   ['V', 'V', 'Ic'],
   ['V', 'V', 'Rc'],
   ['Y', 'Y', 'H'],
   ['Y', 'Y', 'K'],
   ['g', 'g', 'r'],
   ['g', 'g', 'i'],
   ['g', 'g', 'z'],
   ['i', 'g', 'i'],
   ['i', 'u', 'i'],
   ['r', 'g', 'r'],
   ['r', 'u', 'r'],
   ['u', 'u', 'i'],
   ['u', 'u', 'z'],
   ['z', 'r', 'z'],
   ['z', 'g', 'z'],
   ['z', 'u', 'z'],
]

import random
random.seed(999237)
import calc_kcor_2012 as kc
        
print "# generated by kcors.py script"
print "#"
print "# filter redshift c1 c2 cvalue kcor"
for [fname, c1, c2] in opts:
   cname = "%s - %s" % (c1, c2)
   redshift = random.random() * 0.5
   cvalue = (random.random() * 2 - 1) * 1.5
   kcor = kc.calc_kcor(fname, redshift, cname, cvalue)
   print fname, redshift, c1, c2, cvalue, kcor

