package uk.ac.starlink.startask;

import uk.ac.starlink.jpcs.TaskReply;
import net.jini.core.entry.Entry;

/** Information returned by a StarTaskRequest server
*/
public class StarTaskReply implements Entry {

public StarTaskRequestId reqId = null;
public TaskReply taskReply = null;

/** Construct a template StarTaskReply
*/
public StarTaskReply() {
}

/** Construct a complete StarTaskReply
  * @param id the Id of the StarTaskRequest giving rise to this StarTaskReply
  * @param taskReply the TaskReply generated by the StarTaskRequest.
  */
public StarTaskReply( StarTaskRequestId id, TaskReply reply ) {
   reqId = id;
   taskReply = reply;
}

}
