# 
# $Id: Makefile,v 1.2 2002/08/16 22:21:13 brighton Exp $
# 
# who             when        what
# --------------  ----------  ----------------------------------------
# Allan Brighton  1999/12/08  Created

# Resource files (images)
RESOURCES = \
	AstroCat.dtd	\
	logConfig.prop	\
	skycat.cfg	\
        conf/2MASSImg.xml \
        conf/Aladin2MASSImg.xml \
        conf/AladinDSS1Img.xml \
        conf/AladinDSS2Img.xml \
        conf/AstroCat.xml \
        conf/ISSAImg.xml \
        conf/IRASImg.xml \
        conf/MSXImg.xml \
        conf/gsc2_eso.xml \
        conf/nph-catlist.xml \
        images/AlignCenter24.gif \
        images/AscendSort.gif \
        images/Back24.gif \
        images/Bottom16.gif \
        images/Bottom24.gif \
        images/Catalog24.gif \
        images/Copy24.gif \
        images/Cut24.gif \
        images/CutLevels24.gif \
        images/DescendSort.gif \
        images/DownArrow16.gif \
        images/DownArrow24.gif \
        images/Edit16.gif \
        images/Edit24.gif \
        images/FastForward16.gif \
        images/FastForward24.gif \
        images/Forward24.gif \
        images/ImageDisplay24.gif \
        images/Import16.gif \
        images/Import24.gif \
        images/JumpLeft16.gif \
        images/JumpRight16.gif \
        images/NoEdit24.gif \
        images/Open24.gif \
        images/Paste24.gif \
        images/Play16.gif \
        images/Play24.gif \
        images/Print24.gif \
        images/PrintPreview24.gif \
        images/Redo24.gif \
        images/TaskStatusOff.gif \
        images/TaskStatusOn.gif \
        images/Top16.gif \
        images/Top24.gif \
        images/Undo24.gif \
        images/UpArrow16.gif \
        images/UpArrow24.gif \
        images/Zoom24.gif \
        images/ZoomIn24.gif \
        images/ZoomOut24.gif \
	images/archive.gif \
	images/catalog.gif \
        images/ellipse.gif \
        images/flipx.xbm \
        images/flipy.xbm \
        images/freehand.gif \
	images/imagesvr.gif \
        images/left.xbm \
        images/right.xbm \
        images/stars.gif \
        images/JumpLeft16.gif \
        images/JumpRight16.gif \
	images/imagesvr.gif \
        images/line.gif \
	images/local.gif \
        images/magnify.xbm \
	images/namesvr.gif \
	images/nsfolder.gif \
	images/nsopenfold.gif \
        images/polygon.gif \
        images/polyline.gif \
        images/rectangle.gif \
        images/region.gif \
        images/right.xbm \
        images/rotate.xbm \
        images/shrink.xbm \
        images/stars.gif \
	images/symb_arrow.gif \
	images/symb_circle.gif \
	images/symb_compass.gif \
	images/symb_cross.gif \
	images/symb_diamond.gif \
	images/symb_ellipse.gif \
	images/symb_line.gif \
	images/symb_plus.gif \
	images/symb_square.gif \
	images/symb_triangle.gif \
        images/text.gif \
        images/width1.gif \
        images/width2.gif \
        images/width3.gif \
        images/width4.gif \
        colormaps/Aips0.lasc \
        colormaps/Background.lasc \
        colormaps/Blue.lasc \
        colormaps/Blulut.lasc \
        colormaps/Color.lasc \
        colormaps/Green.lasc \
        colormaps/Heat.lasc \
        colormaps/Idl11.lasc \
        colormaps/Idl12.lasc \
        colormaps/Idl14.lasc \
        colormaps/Idl15.lasc \
        colormaps/Idl2.lasc \
        colormaps/Idl4.lasc \
        colormaps/Idl5.lasc \
        colormaps/Idl6.lasc \
        colormaps/Isophot.lasc \
        colormaps/Light.lasc \
        colormaps/Manycolor.lasc \
        colormaps/Pastel.lasc \
        colormaps/Rainbow.lasc \
        colormaps/Rainbow1.lasc \
        colormaps/Rainbow2.lasc \
        colormaps/Rainbow3.lasc \
        colormaps/Rainbow4.lasc \
        colormaps/Ramp.lasc \
        colormaps/Random.lasc \
        colormaps/Random1.lasc \
        colormaps/Random2.lasc \
        colormaps/Random3.lasc \
        colormaps/Random4.lasc \
        colormaps/Random5.lasc \
        colormaps/Random6.lasc \
        colormaps/Real.lasc \
        colormaps/Red.lasc \
        colormaps/Smooth.lasc \
        colormaps/Smooth1.lasc \
        colormaps/Smooth2.lasc \
        colormaps/Smooth3.lasc \
        colormaps/Staircase.lasc \
        colormaps/Stairs8.lasc \
        colormaps/Stairs9.lasc \
        colormaps/Standard.lasc \
	\
	colormaps/Equal.iasc \
        colormaps/Exponential.iasc \
        colormaps/Gamma.iasc \
        colormaps/Jigsaw.iasc \
        colormaps/Lasritt.iasc \
        colormaps/Log.iasc \
        colormaps/Negative.iasc \
        colormaps/NegativeLog.iasc \
        colormaps/Null.iasc \
        colormaps/Ramp.iasc \
        colormaps/Stairs.iasc \



# Java package name
PACKAGE_DIR = resources

# Path to top level dir
TOP = ..

# include master makefile
include $(TOP)/conf/master.mk
