#!/bin/sh
#+
#  Name:
#     apidocs

#  Purpose:
#     Display the provisional SPLAT API documentation.

#  Description:
#     Locates and displays the API documentation. This should be
#     found in SPLAT documents directory "programming.htx". This is
#     just a wrapper that gets the "showme" command to look in the right
#     place.

#  Type of Module:
#     Shell script.

#  Copyright:
#     Copyright (C) 2001 Central Laboratory of the Research Councils

#  Authors:
#     PWD: P.W. Draper (Starlink, Durham University)
#     {enter_new_authors_here}

#  History:
#     20-DEC-2001 (PWD):
#        Original version.
#     {enter_further_changes_here}

#  Bugs:
#     {note_any_bugs_here}

#-

#  Skip the definition of SPLAT_DIR if it's in the standard place for
#  old-SPLAT. Remove this when new SPLAT is the official release.
if test "$SPLAT_DIR" = "/star/bin/splat" \
        -o "$SPLAT_DIR" = "/stardev/bin/splat" ; then
  SPLAT_DIR=""
fi

#  Locate this script or SPLAT_DIR to find our jar files etc.
if test -z "$SPLAT_DIR"; then
   SPLAT_DIR=`dirname $0`
fi
echo "SPLAT_DIR = $SPLAT_DIR"

showme $SPLAT_DIR/../../docs/splat/programming.htx
exit
