#!/bin/sh
#+
#  Name:
#     starlocation

#  Purpose:
#     Echo the location of this script

#  Description:
#     Reports where this script is located. Should be the starjava bin
#     directory. Useful for "sourced" scripts which cannot locate
#     themselves using "dirname $0".

#  Type of Module:
#     Bourne shell script.

#  Copyright:
#     Copyright (C) 2003 Central Laboratory of the Research Councils

#  Authors:
#     PWD: P. W. Draper (Starlink, Durham University)
#     {enter_new_authors_here}

#  History:
#     03-JUN-2003 (PWD):
#        Original version.
#     {enter_further_changes_here}

#  Bugs:
#     {note_any_bugs_here}

#-
echo `dirname $0`
exit
