#!/bin/sh
#+
#  Name:
#     starlocation

#  Purpose:
#     Echo the location of this script

#  Type of Module:
#     Bourne shell script.

#  Description:
#     Reports where this script is located. Should be the starjava bin
#     directory. Useful for "sourced" scripts which cannot locate
#     themselves using "dirname $0".

#  Copyright:
#     Copyright (C) 2003 Central Laboratory of the Research Councils.
#     All Rights Reserved.

#  Licence:
#     This program is free software; you can redistribute it and/or
#     modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation; either version 2 of
#     the License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied
#     warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
#     PURPOSE. See the GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 59 Temple Place,Suite 330, Boston, MA
#     02111-1307, USA

#  Authors:
#     PWD: P. W. Draper (Starlink, Durham University)
#     {enter_new_authors_here}

#  History:
#     03-JUN-2003 (PWD):
#        Original version.
#     {enter_further_changes_here}

#-
echo `dirname $0`
exit
