#! /bin/sh
# This searches a search database.  Argument is the database directory

# Cygwin support.  $cygwin _must_ be set to either true or false.
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  *) cygwin=false ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin; then
  [ -n "$JAVAHELP_HOME" ] &&
    JAVAHELP_HOME=`cygpath --unix "$JAVAHELP_HOME"`
fi

if [ "$JAVAHELP_HOME" = "" ] ; then
  JAVAHELP_HOME=`dirname $0`
fi

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  JAVAHELP_HOME=`cygpath --path --windows "$JAVAHELP_HOME"`
fi

java -cp $JAVAHELP_HOME/../../lib/help/jhall.jar com.sun.java.help.search.QueryEngine "$@"

exit
