#!/bin/sh -xv

# Import the dom4j docs directory. May want to track these as third
# party changes. 
CVS_RSH=ssh
export CVS_RSH
cd docs
cvs  -d :ext:pwd@rlsaxps.bnsc.rl.ac.uk:/home/soft3/cvs \
   import -ko -I! -m "dom4j docs" java/source/dom4j/docs DOM4J Dom4j_Docs_V1
