#!/bin/sh

#  Script to start the SOG application. If not set the position of
#  this script is taken to be in the SOG part of the standard Starlink
#  Java "bin" directory and will be used to locate the application
#  jar file.

echo "Starting SOG"

#  Find where this script is located, this is SOG_DIR, unless SOG_DIR
#  is already set (SOG_DIR used to locate the "starjava" script)

if test -z "$SOG_DIR"; then
   SOG_DIR=`dirname $0`
fi
echo "SOG_DIR = $SOG_DIR"

#  Locate the application jar file. This is relative to this script or
#  SOG_DIR.
appjar="$SOG_DIR/../../lib/sog/sog.jar"
if test ! -f "$appjar"; then
   echo "Failed to locate the SOG application. Please define SOG_DIR"
   exit
fi

# Make sure that we get the installed shareable libraries.
if test -z "$LD_LIBRARY_PATH"; then
   LD_LIBRARY_PATH=${SOG_DIR}/../../lib
else
   LD_LIBRARY_PATH=${SOG_DIR}/../../lib:${LD_LIBRARY_PATH}
fi
export LD_LIBRARY_PATH

#  Run up SOG.
sog_port=8082
$SOG_DIR/starjava \
 -Daxis.EngineConfigFactory=uk.ac.starlink.soap.AppEngineConfigurationFactory \
 -Daxis.ServerFactory=uk.ac.starlink.soap.AppAxisServerFactory \
 -jar $appjar -port $sog_port $*
