#!/bin/sh

#  Note JVM seems to depend on /bin/sh signature, do not remove.

#+
#  Name:
#     mk
#
#  Version:
#     Version for Mk V library makefile.
#
#  Purpose:
#     Invoke make to build and install the TREEVIEW package.
#
#  Type of Module:
#     Shell script.
#
#  Description:
#     This script should normally be used to invoke the make utility
#     to build and install the TREEVIEW package and to perform other
#     housekeeping tasks.  It invokes the make utility after first
#     defining appropriate environment variables and macros for the
#     computer system in use.  This file also serves to document the
#     systems on which TREEVIEW is implemented.
#
#  Invocation:
#     The user of this script should normally first define the SYSTEM
#     environment variable to identify the host computer system (see
#     the "Supported Systems" section).  This script should then be used
#     in the same way as the make utility would be used.  For instance,
#     to build, install and test TREEVIEW, you might use the following
#     commands:
#
#        ./mk build
#        ./mk install
#        ./mk test
#        ./mk clean
#
#  Supported Systems:
#     The following systems are currently supported and may be
#     identified by defining the SYSTEM environment variable
#     appropriately before invoking this script:
#
#        alpha_OSF1
#           DEC Alpha machines running OSF1
#
#        ix86_Linux
#           Intel PC machines running Linux
#
#        sun4_Solaris
#           SUN Sparcstations running SunOS 5.x (Solaris)
#
#  Targets:
#     For details of what targets are provided, see the associated
#     makefile.  The latter will normally provide a default target
#     called "help", which outputs a message describing this script
#     and lists the targets provided.
#
#  Notes on Porting:
#     If your machine or system setup does not appear in this script,
#     then it should be possible to build and install TREEVIEW by
#     adding a new case to this script with appropriate definitions
#     (probably based on one of the existing implementations).
#
#  make Macros:
#     The following "global" make macros are used in the associated
#     makefile and may be changed by means of appropriate environment
#     variable definitions (in each case the default is shown in
#     parentheses).  Note that these macros are provided to allow
#     external control over the directories in which software is
#     installed, etc., so they should not normally be re-defined within
#     this script.
#
#        STARLINK (/star)
#           Pathname of the root directory beneath which Starlink
#           software is currently installed.  This indicates to
#           TREEVIEW where to find other Starlink software (include
#           files, libraries, etc.) which it uses.
#
#        INSTALL ($HOME)
#           Pathname of the root directory beneath which TREEVIEW will
#           be installed for use.  Your home directory will be used by
#           default.  This macro is provided to allow TREEVIEW to be
#           installed locally for personal use (e.g. during development
#           or testing).  It should be set to the $STARLINK directory if
#           you want to add TREEVIEW into an already installed set of
#           Starlink software.  You should ensure that the appropriate
#           sub-directories appear on any relevant search paths which
#           your system uses for locating software (e.g. binaries and
#           libraries).
#
#        EXPORT (.)
#           Pathname of the directory into which compressed tar files
#           will be written if the "export" or "export_source" make
#           targets are used to produce an exportable copy of TREEVIEW
#           or its source files.  The current working directory (i.e.
#           the TREEVIEW source directory) will be used by default.
#
#        STAR_JRE ($STARLINK/java/j2re1.4.0)
#           Top of the Java Runtime Environment tree.
#
#        STAR_JDK ($STARLINK/java/j2sdk1.4.0)
#           Top of the Java Software Developers Kit tree.
#
#     The following "local" make macros are used in the associated
#     makefile and should normally be overridden by environment variable
#     definitions within this script.  All the local macros that are
#     used in building a package should overridden even when the value
#     is the same as the default.  This documents which macros are used
#     and ensures that the package will continue to build correctly even
#     if the default values are changed.  Macros that are not used on a
#     particular machine (e.g. BLD_SHR on DECstations) should not be
#     overridden.  In each case the default is shown in parentheses.
#
#        AR_IN (ar -r)
#           The command to use to insert an object (.o) file into an
#           archive (.a) library.  On some systems the variation 'ar r'
#           may be required instead.
#
#        BLD_SHR (:)
#           Command to build a shareable library when given three
#           arguments specifying (1) the name of the library file to be
#           built (2) a list of the object files to be used in the
#           library and (3) a list of any additional libraries against
#           which to link.  By default, it is assumed that shareable
#           libraries are not available, and the default acts as a null
#           command.
#
#        CC (c89)
#           The C compiler command to use.
#
#        CFLAGS (-O)
#           The C compiler options to use.
#
#        LINK (ln)
#           The command required to establish a link to a file.  The
#           default assumes POSIX.2 behavior, which only provides a
#           "hard" link operating within a single file system.  If the
#           host operating system allows "symbolic" links, then this
#           macro might be re-defined as 'ln -s'.  Alternatively, if the
#           use of multiple file systems is essential but not supported
#           by any form of link, then a copy command could be
#           substituted (e.g. 'cp -p'), at some cost in file space.
#
#        SHARE (.so)
#           The file type suffix to be applied to produce the name of a
#           shareable library file.  By default, the ".so" suffix is
#           applied without a library version number.  For systems which
#           support version numbers on shareable libraries, the macro
#           LIB_VERS is defined within the associated makefile and may
#           be used as part of a definition such as '.so.$(LIB_VERS)'.
#
#        TAR_IN (pax -w -v -x ustar -f)
#           Command to use to insert a file into a .tar archive file.
#           The default uses the POSIX.2 pax command, which is not
#           available on traditional UNIX systems.  These typically use
#           a tar command such as 'tar -cvhf' instead (if symbolic
#           links are supported, then an option to follow these must be
#           included in this command).
#
#        TAR_OUT (pax -r -f)
#           Command to use to extract a file from a .tar archive file.
#           The default uses the POSIX.2 pax command, which is not
#           available on traditional UNIX systems.  These typically use
#           a tar command such as 'tar -xf' instead.
#
#  Implementation Deficiencies:
#     -  The implementation of shareable libraries on the alpha_OSF1
#        system is still preliminary.
#
#  Copyright:
#     Copyright (C) 1995-2001 Central Laboratory of the Research Councils
#
#  Authors:
#     RFWS: R.F.Warren-Smith (Starlink, RAL)
#     PMA: P.M.Allan (Starlink, RAL)
#     PTW: P.T.Wallace (Starlink, RAL)
#     BLY: M.J.Bly (Starlink, RAL)
#     AJC: A.J.Chipperfield (Starlink, RAL)
#     PWD: Peter W. Draper (Starlink, Durham University)
#     BC:  Brad Cavanagh (Joint Astronomy Centre)
#     {enter_new_authors_here}
#
#  History:
#     4-JAN-1993 (RFWS):
#        Original version.
#     15-MAR-1993 (RFWS):
#        Adapted for use on sun4_Solaris and alpha_OSF1.
#     30-JUN-1993 (PMA):
#        Added definitions of CC and CFLAGS for all machines.
#     13-OCT-1993 (PMA):
#        Added comments about definitions of CC and CFLAGS for all machines.
#     15-NOV-1993 (PTW):
#        Cosmetics.
#     2-MAY-1995 (BLY):
#        Modified RANLIB default to : (colon).
#        Modified BLD_SHR default to : (colon).
#     16-JUN-1995 (BLY):
#        Designated Mk IVb version.
#     21-JUN-1995 (AJC):
#        Remove references to /star in CFLAGS.
#     12-DEC-1996 (BLY):
#        Linux case added.
#     23-OCT-2001 (PWD):
#        Now for SPLAT.
#     29-OCT-2001 (MBT):
#        Adapted for TREEVIEW.
#     25-OCT-2006 (BC):
#        Added support for Mac OS X on i386.
#     04-FEB-2008 (PWD):
#        Merge support for MacOSX_ppc and MacOSX_i386. Cannot invoke
#        these targets independently (requires JAVA_SYSTEM to be defined).
#     {enter_further_changes_here}
#
#  Bugs:
#     {note_any_bugs_here}
#
#-

#  Export "local" definitions to the environment for use by make.
      export AR_IN
      export BLD_SHR
      export CC
      export CFLAGS
      export JAVA_SYSTEM
      export JAVA_INCLUDE
      export JAVA_SYSTEM_INCLUDE
      export LINK
      export SOURCE_VARIANT
      export RANLIB
      export SHARE
      export TAR_IN
      export TAR_OUT
      export STARJAVA_LIB

#  Check that the SYSTEM environment variable is defined.
      if test "$SYSTEM" = ""; then
         echo "mk: Please define the environment variable SYSTEM to identify"
         echo "    your computer system (the prologue in the mk script file"
         echo "    contains more information if you require it)."

#  If OK, test for each recognised system.
      else
         case "$SYSTEM" in

#  DEC Alpha:
#  =========
#  DEC Alpha machines running OSF1.
#  -------------------------------
            alpha_OSF1)
               AR_IN='ar -r'
               BLD_SHR='f() ld -shared -o $$1 $$2 $$3 -lfor -lFutil -lUfor -lm -lots -lc; f'
               CC='cc'
               CFLAGS='-I. $(ADDINCS) -I$(JAVA_INCLUDE) -I$(JAVA_SYSTEM_INCLUDE) -I$(STAR_INC) -O -pthread'
               LINK='ln -s'
               RANLIB='ranlib'
               SHARE='.so'
               TAR_IN='tar -cvhf'
               TAR_OUT='tar -xf'
               JAVA_SYSTEM='alpha'
               echo "mk: Environment variables defined for $SYSTEM system"
               ;;

#  SUN Sparcstations running SunOS 5.x (Solaris).
#  ---------------------------------------------
            sun4_Solaris)
               AR_IN='ar -r'
               BLD_SHR='f() $(CC) -G -o $$1 $$2 -lm; f'
               CC='cc'
               CFLAGS='-I. $(ADDINCS) -I$(JAVA_INCLUDE) -I$(JAVA_SYSTEM_INCLUDE) -I$(STAR_INC) -g -K PIC'
               LINK='ln -s'
               SHARE='.so'
               TAR_IN='tar -cvhf'
               TAR_OUT='tar -xf'
               JAVA_SYSTEM='solaris'
               echo "mk: Environment variables defined for $SYSTEM system"
               ;;

#  PC systems:
#  ==========
#  Intel PC running Linux.
#  ----------------------
            ix86_Linux)
               AR_IN='ar r'
               BLD_SHR='f() { $(CC) -shared -o $$1 $$2 -lm;}; f'
               CC='gcc'
               CFLAGS='-I. $(ADDINCS) -I$(JAVA_INCLUDE) -I$(JAVA_SYSTEM_INCLUDE) -I$(STAR_INC) -O -fPIC'
               LINK='ln -s'
               RANLIB='ranlib'
               SHARE='.so'
               TAR_IN='tar -cvhf'
               TAR_OUT='tar -xf'
               JAVA_SYSTEM='linux'
               echo "mk: Environment variables defined for $SYSTEM system"
               ;;

#  Mac OS X ppc and i386.
#  ----------------------
            MacOSX)
               AR_IN='ar r'
               BLD_SHR='f() { $(CC) -arch $(JAVA_SYSTEM) -framework JavaVM -dynamiclib -install_name $(STARJAVA_LIB)/`basename $$1` -single_module -flat_namespace -undefined suppress -o $$1 $$2 ;}; f'
               CC='gcc'
               CFLAGS='-I/System/Library/Frameworks/JavaVM.framework/Headers -arch $(JAVA_SYSTEM) -I. $(ADDINCS) -I$(JAVA_INCLUDE) -I$(JAVA_SYSTEM_INCLUDE) -I$(STAR_INC) -g'
               LINK='ln -s'
               RANLIB='ranlib'
               SHARE='.jnilib'
               TAR_IN='tar -cvhf'
               TAR_OUT='tar -xf'
               f="`find $JAVA_HOME -name jni.h`"
               JAVA_INCLUDE="`dirname $f`"
               f="`find $JAVA_HOME -name jni_md.h`"
               JAVA_SYSTEM_INCLUDE="`dirname $f`"
               echo "mk: Environment variables defined for $SYSTEM system"
               ;;

#  Issue a warning if SYSTEM is not recognised.
            *)
               SOURCE_VARIANT='unknown'
               echo "mk: WARNING: value of SYSTEM = $SYSTEM not recognised..."
               echo "             ...assuming default system characteristics"
               echo '             ...setting SOURCE_VARIANT to "unknown"'
               ;;
         esac

#  Invoke make with the appropriate environment variables set to override
#  default macros defined in the makefile.
         echo make -e $*
         make -e $*
      fi

#  End of script.
