# Makefile

# Source files to compile
SOURCES = \
	MinMaxDescriptor.java  \
	MinMaxOpImage.java  \
	CutLevelDescriptor.java  \
	CutLevelOpImage.java  \
	ImageOps.java

# Java package name
PACKAGE_DIR = jsky/image/operator

# Path to top level dir
TOP = ../../../..

# include master makefile
include $(TOP)/conf/master.mk
