# ESO Archive
# 
# $Id: Makefile,v 1.5 2002/08/08 22:40:23 gillies Exp $
# 
# who             when        what
# --------------  ----------  ----------------------------------------
# Allan Brighton  1999/12/08  Created

# Source files to compile
SOURCES = \
	AbstractScienceObject.java \
	AbstractScienceObjectNode.java \
	AbstractWavelength1D.java \
	Constants.java \
	Coordinates.java \
	CoordinatesOffset.java \
	Flux.java \
	IQE.java \
	MathUtilities.java \
	MrqFit.java \
	Passband.java \
	ProperMotion.java \
	Quantity.java \
	QuantityRange.java \
	Redshift.java \
	ScienceObjectModel.java \
	ScienceObjectNodeModel.java \
	Spectrum.java \
	Spectrum1DArray.java \
	Time.java \
	UnitsNotSupportedException.java \
	Wavelength.java \
	Wavelength1DArray.java \
	Wavelength1DArrayParser.java \
	Wavelength1DFormula.java \
	Wavelength1DModel.java \
	WavelengthArrayParseException.java \
	WavelengthArrayParserAsciiPairs.java \
	WavelengthArrayParserFitsHst.java \
	WavelengthNotInPassbandException.java \


# Java package name
PACKAGE_DIR = jsky/science

# Path to top level dir
TOP = ../../..

# include master makefile
include $(TOP)/conf/master.mk

# (see ./gui for tests)
test:

