#!/bin/csh 

#  Convert Latex SUN243 into hypertext for the on-line docs and help
#  system.

setenv HTX_EMAIL '<A HREF="mailto:splat@star.rl.ac.uk">splat@star.rl.ac.uk</A>'

set copyr1="Copyright (C) 2001-2005 Council for the Central Laboratory of the Research Councils"
set copyr2="Copyright (C) 2006-2007 Particle Physics and Astronomy Research Council"
set copyr3="Copyright (C) 2007-2009 Science and Technology Facilities Council"

setenv COPYRIGHT "$copyr1<br>$copyr2<br>$copyr3"

#  Copy figures into place (directory in CVS).
\cp gifs/* sun243.htx

#  Help system docs, these need to be in a jar file so we can 
#  access them from javahelp? Figures?
echo "star2html -no_navigation -c "$COPYRIGHT" sun243.tex"

#exit(0)
star2html -no_navigation -c "$COPYRIGHT" sun243.tex

./makeSearchDatabase
jar cf splat_help.jar sun243.htx HelpSet.hs TOC.xml Map.jhm JavaHelpSearch
\mv splat_help.jar ../lib

#echo "Created JavaHelp archives"

#  Normal docs. Note remove files that change trivially to stop
#  unneccesary updates.
star2html -c "$COPYRIGHT" sun243.tex
\rm sun243.htx/images.*
tar cf sun243.htx_tar sun243.htx
gzip -f -9 sun243.htx_tar

star2html -c "$COPYRIGHT" programming.tex
tar cf programming.htx_tar programming.htx
gzip -f -9 programming.htx_tar

echo "Created hypertext archives"
