#!/bin/csh 

#  Convert Latex SUN243 into hypertext for the on-line docs and help
#  system.

setenv HTX_EMAIL '<A HREF="mailto:splat@star.rl.ac.uk">splat@star.rl.ac.uk</A>'

#  Help system docs, these need to be in a jar file so we can 
#  access them from javahelp? Figures?
star2html -no_navigation sun243.tex
./makeSearchDatabase
jar cf splat_help.jar sun243.htx HelpSet.hs TOC.xml Map.jhm JavaHelpSearch
\mv splat_help.jar ../lib

echo "Created JavaHelp archives"

#  Normal docs.
star2html sun243.tex
\cp gifs/* sun243.htx
tar cf sun243.htx_tar sun243.htx
gzip -f -9 sun243.htx_tar

star2html programming.tex
tar cf programming.htx_tar programming.htx
gzip -f -9 programming.htx_tar

echo "Created hypertext archives"

