# ESO Archive
# 
# $Id: Makefile,v 1.3 2002/08/08 22:40:23 gillies Exp $
# 
# who             when        what
# --------------  ----------  ----------------------------------------
# Allan Brighton  1999/12/08  Created

# Source files to compile
SOURCES = \
	ShapeUtilities.java


# Java package name
PACKAGE_DIR = jsky/util/java2d

# Path to top level dir
TOP = ../../../..

# include master makefile
include $(TOP)/conf/master.mk

# tests
test: 

