#!/bin/sh

#+
#  Name:
#     targetdeps

#  Purpose:
#     Perform an ANT target on a package and all the packages that it
#     depends on. 

#  Description:
#     Uses the "packagedeps" command to obtain a list of all the
#     packages that the named package depends on. It then runs ANT on
#     all the packages. The first parameter should be the name of a
#     package, and the second the target to execute. If the second is
#     not defined this will default to "export-runonly".
#
#     Note this must be run from the "source" directory.

#  Type of Module:
#     Shell script.

#  Copyright:
#     Copyright (C) 2003 Central Laboratory of the Research Councils

#  Authors:
#     PWD: P.W. Draper (Starlink, Durham University)
#     {enter_new_authors_here}

#  History:
#     30-SEP-2003 (PWD):
#        Original version.
#     {enter_further_changes_here}

#  Bugs:
#     {note_any_bugs_here}

#-

if test "$1" = ""; then 
   echo "Usage: ./scripts/targetdeps package"
   exit
fi

if test "$2" = ""; then 
   target="export-runonly"
else
   target="$2"
fi

#  Get the list of packages (should be in "package".depends).
dependsfile="${1}.depends"
if test -f $dependsfile; then
   rm $dependsfile
fi

#  Invoke the main package
echo
echo "--- $target $uppername ---"
(cd $1; ant $target)

#  Get the dependency packages.
echo
echo "--- Dependencies ---"
./scripts/packagedeps $1

#  And invoke them too.
if test -f $dependsfile; then
   for f in `cat $dependsfile`; do
      if test -d $f -a "$1" != "$f" ; then
         echo
         echo "--- $target $f ---"
         (cd $f; ant $target)
      fi
   done
fi
exit
