#!/bin/sh -xv

# Import the AXIS docs and webapps directories. May want to track
# these as third party changes.
CVS_RSH=ssh
export CVS_RSH
cd docs
cvs  -d :ext:pwd@cvs.starlink.ac.uk:/cvs \
   import -ko -I! -m "Axis docs" java/source/axis/docs/axis AXIS Axis_Docs_V1RC1
exit
cd ..
cd webapps
cvs -d :ext:pwd@cvs.starlink.ac.uk:/cvs \
   import -ko -I! -m "Axis webapps" java/source/axis/webapps AXIS Axis_Webapp_V1RC1

