#!/bin/csh 

#  Convert Latex SUN243 into hypertext for the on-line docs and help
#  system.

setenv HTX_EMAIL '<A HREF="mailto:frog@starlink.ac.uk">frog@starlink.ac.uk</A>'

# make sure we have a clean build
# 
\rm -rf sun254.fig/.xvpics
\rm -rf sun254.fig/*.eps
\rm -f *.bck

# rebuild the EPS files
unalias convert

convert -page A4 -geometry 75% \
    sun254.fig/splash.gif eps:sun254.fig/splash.eps

convert -page A4 -geometry 75% \
    sun254.fig/main_window.gif eps:sun254.fig/main_window.eps

# build sun254.htx from the LaTeX file
#
latex sun254
latex sun254
dvips -o sun254.ps sun254
star2html sun254
hlink

#  make the search db
#
if ( -e sun254.htx/icons.html ) then
  \rm sun254.htx/icons.html
endif

/work/java/jh2.0/javahelp/bin/jhindexer sun254.htx

#  Help system docs, these need to be in a jar file so we can 
#  access them from javahelp? Figures?

jar cf frog_help.jar FrogHelpSet.hs JavaHelpSearch Map.jhm TOC.xml \
       sun254.fig sun254.htx 
mv frog_help.jar ../lib/

echo "Created JavaHelp archives"

