#!/bin/sh
# runPack Class method arguments...
#
# To run a java Starlink task in a separate shell
# The first two arguments give the Class and method. The Class may be specified
# as 'package.Class', where package is the Starlink package name. 'package.' may
# be omitted in which case it is assumed that the package is the classname in
# lower case.
# The remaining arguments are passed to the method.
#
# Examples:
#    runPack Kappa stats comwest
#    runPack startask.ShellRunner rundisplay comwest device=xw mode=p
#

   pack=`echo $1 | sed 's/\..*//'`
   class=`echo $1 | sed 's/.*\.//;'`

   if [ "$pack" = "$class" ]; then
      pack=`echo $class | tr '[:upper:]' '[:lower:]'`
   fi
   shift

   method=$1
   shift

   if [ -z "$STARJAVA" ]; then 
      if [ -d /stardev ]; then
         STARJAVA="/stardev/starjava"
      else
         STARJAVA="/star/starjava"
      fi
   fi
   export STARJAVA

   java -Dstar.ShellRunner=true \
    -jar $STARJAVA/lib/${pack}/${pack}.jar $method "$@"
   

