/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_starlink_splat_imagedata_NDFJ */

#ifndef _Included_uk_ac_starlink_splat_imagedata_NDFJ
#define _Included_uk_ac_starlink_splat_imagedata_NDFJ
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_ac_starlink_splat_imagedata_NDFJ_serialVersionUID
#define uk_ac_starlink_splat_imagedata_NDFJ_serialVersionUID 7112558037504787639LL
#undef uk_ac_starlink_splat_imagedata_NDFJ_BADF
#define uk_ac_starlink_splat_imagedata_NDFJ_BADF -3.4028235E38f
#undef uk_ac_starlink_splat_imagedata_NDFJ_BADD
#define uk_ac_starlink_splat_imagedata_NDFJ_BADD -1.7976931348623157E308
#undef uk_ac_starlink_splat_imagedata_NDFJ_BADI
#define uk_ac_starlink_splat_imagedata_NDFJ_BADI -2147483648L
#undef uk_ac_starlink_splat_imagedata_NDFJ_BADS
#define uk_ac_starlink_splat_imagedata_NDFJ_BADS -32768L
#undef uk_ac_starlink_splat_imagedata_NDFJ_BADB
#define uk_ac_starlink_splat_imagedata_NDFJ_BADB -128L
#undef uk_ac_starlink_splat_imagedata_NDFJ_DOUBLE
#define uk_ac_starlink_splat_imagedata_NDFJ_DOUBLE 0L
#undef uk_ac_starlink_splat_imagedata_NDFJ_FLOAT
#define uk_ac_starlink_splat_imagedata_NDFJ_FLOAT 1L
#undef uk_ac_starlink_splat_imagedata_NDFJ_INTEGER
#define uk_ac_starlink_splat_imagedata_NDFJ_INTEGER 2L
#undef uk_ac_starlink_splat_imagedata_NDFJ_SHORT
#define uk_ac_starlink_splat_imagedata_NDFJ_SHORT 3L
#undef uk_ac_starlink_splat_imagedata_NDFJ_BYTE
#define uk_ac_starlink_splat_imagedata_NDFJ_BYTE 4L
/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nInit
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nOpen
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nOpenNew
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nOpenNew
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nClose
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetType
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetType
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nHas
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nHas
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetDims
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetDims
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet1DDouble
 * Signature: (ILjava/lang/String;Z)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet1DDouble
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nSet1DDouble
 * Signature: (ILjava/lang/String;[D)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nSet1DDouble
  (JNIEnv *, jclass, jint, jstring, jdoubleArray);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet1DFloat
 * Signature: (ILjava/lang/String;Z)[F
 */
JNIEXPORT jfloatArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet1DFloat
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet1DInt
 * Signature: (ILjava/lang/String;Z)[I
 */
JNIEXPORT jintArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet1DInt
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet1DShort
 * Signature: (ILjava/lang/String;Z)[S
 */
JNIEXPORT jshortArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet1DShort
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet1DByte
 * Signature: (ILjava/lang/String;Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet1DByte
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet2DDouble
 * Signature: (ILjava/lang/String;Z)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet2DDouble
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet2DFloat
 * Signature: (ILjava/lang/String;Z)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet2DFloat
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet2DInt
 * Signature: (ILjava/lang/String;Z)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet2DInt
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet2DShort
 * Signature: (ILjava/lang/String;Z)[[S
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet2DShort
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet2DByte
 * Signature: (ILjava/lang/String;Z)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet2DByte
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetAstArray
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetAstArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetAst
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetAst
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nSetAstArray
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nSetAstArray
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nSetAst
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nSetAst
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetCharComp
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetCharComp
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nSetCharComp
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nSetCharComp
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetTemp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetTemp
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetCopy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetCopy
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGet1DNewDouble
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGet1DNewDouble
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nHasExtension
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nHasExtension
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nAccessFitsHeaders
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nAccessFitsHeaders
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nCountFitsHeaders
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nCountFitsHeaders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nGetFitsHeader
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nGetFitsHeader
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nReleaseFitsHeaders
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nReleaseFitsHeaders
  (JNIEnv *, jclass, jlong);

/*
 * Class:     uk_ac_starlink_splat_imagedata_NDFJ
 * Method:    nCreateFitsExtension
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_uk_ac_starlink_splat_imagedata_NDFJ_nCreateFitsExtension
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
