#!/bin/sh -xv

# Import the JSky docs directory. May want to track these as third
# party changes. 
CVS_RSH=ssh
export CVS_RSH
cd docs
cvs  -d :ext:pwd@rlsaxps.bnsc.rl.ac.uk:/home/soft3/cvs \
   import -ko -I! -m "JSky docs" java/source/jsky/docs JSky JSky_Docs_V1
