
/* ******************************************************************
 *                         DO NOT EDIT!                             *
 *       This file is autogenerated from AstException.pl            *
 *               and built under Ant control                        *
 ********************************************************************/

#include <stdlib.h>
#include <string.h>
#include "jni.h"
#include "ast.h"
#include "sae_par.h"
#include "uk_ac_starlink_ast_AstException.h"

#define TRY_CONST(Xident) \
   if ( strcmp( #Xident, ident ) == 0 ) { \
      result = (jint) Xident; \
      success = 1; \
   }

JNIEXPORT jint JNICALL Java_uk_ac_starlink_ast_AstException_getErrConst(
   JNIEnv *env,          /* Interface pointer */
   jclass class,         /* The class */
   jstring jIdent        /* Name identifying the error constant */
) {
   jint result = (jint) SAI__OK;
   int success = 0;
   const char *ident = (*env)->GetStringUTFChars( env, jIdent, NULL );
   if ( ident != NULL ) {
      TRY_CONST(SAI__OK) 
      else TRY_CONST(SAI__ERROR)
      else TRY_CONST(AST__ATGER)
      else TRY_CONST(AST__ATSER)
      else TRY_CONST(AST__ATTIN)
      else TRY_CONST(AST__AXIIN)
      else TRY_CONST(AST__BADAT)
      else TRY_CONST(AST__BADBX)
      else TRY_CONST(AST__BADIN)
      else TRY_CONST(AST__BADNI)
      else TRY_CONST(AST__BADNO)
      else TRY_CONST(AST__BADPW)
      else TRY_CONST(AST__BADSM)
      else TRY_CONST(AST__BADWM)
      else TRY_CONST(AST__BDBRK)
      else TRY_CONST(AST__BDFMT)
      else TRY_CONST(AST__BDFTS)
      else TRY_CONST(AST__BDOBJ)
      else TRY_CONST(AST__CLPAX)
      else TRY_CONST(AST__CORNG)
      else TRY_CONST(AST__CVBRK)
      else TRY_CONST(AST__DIMIN)
      else TRY_CONST(AST__DTERR)
      else TRY_CONST(AST__ENDIN)
      else TRY_CONST(AST__EOCHN)
      else TRY_CONST(AST__EXPIN)
      else TRY_CONST(AST__FCRPT)
      else TRY_CONST(AST__FMTER)
      else TRY_CONST(AST__FRMIN)
      else TRY_CONST(AST__FRSIN)
      else TRY_CONST(AST__FTCNV)
      else TRY_CONST(AST__GRFER)
      else TRY_CONST(AST__INHAN)
      else TRY_CONST(AST__INNCO)
      else TRY_CONST(AST__INTER)
      else TRY_CONST(AST__INTRD)
      else TRY_CONST(AST__LDERR)
      else TRY_CONST(AST__LUTII)
      else TRY_CONST(AST__LUTIN)
      else TRY_CONST(AST__MEMIN)
      else TRY_CONST(AST__MTR23)
      else TRY_CONST(AST__MTRAX)
      else TRY_CONST(AST__MTRML)
      else TRY_CONST(AST__MTRMT)
      else TRY_CONST(AST__NAXIN)
      else TRY_CONST(AST__NCHIN)
      else TRY_CONST(AST__NCOIN)
      else TRY_CONST(AST__NCPIN)
      else TRY_CONST(AST__NELIN)
      else TRY_CONST(AST__NOCTS)
      else TRY_CONST(AST__NODEF)
      else TRY_CONST(AST__NOFTS)
      else TRY_CONST(AST__NOMEM)
      else TRY_CONST(AST__NOPTS)
      else TRY_CONST(AST__NOWRT)
      else TRY_CONST(AST__NPTIN)
      else TRY_CONST(AST__OBJIN)
      else TRY_CONST(AST__OPT)
      else TRY_CONST(AST__PDSIN)
      else TRY_CONST(AST__PLFMT)
      else TRY_CONST(AST__PRMIN)
      else TRY_CONST(AST__PTRIN)
      else TRY_CONST(AST__PTRNG)
      else TRY_CONST(AST__RDERR)
      else TRY_CONST(AST__REMIN)
      else TRY_CONST(AST__SCSIN)
      else TRY_CONST(AST__SELIN)
      else TRY_CONST(AST__SLAIN)
      else TRY_CONST(AST__TRNND)
      else TRY_CONST(AST__UNMQT)
      else TRY_CONST(AST__VSMAL)
      else TRY_CONST(AST__WCSAX)
      else TRY_CONST(AST__WCSNC)
      else TRY_CONST(AST__WCSPA)
      else TRY_CONST(AST__WCSTY)
      else TRY_CONST(AST__XSOBJ)
      else TRY_CONST(AST__ZOOMI)
      else TRY_CONST(AST__BADCI)
      else TRY_CONST(AST__ILOST)
      else TRY_CONST(AST__ITFER)
      else TRY_CONST(AST__ITFNI)
      else TRY_CONST(AST__MBBNF)
      else TRY_CONST(AST__MRITF)
      else TRY_CONST(AST__OCLUK)
      else TRY_CONST(AST__UNFER)
      else TRY_CONST(AST__URITF)
      else TRY_CONST(AST__GBDIN)
      else TRY_CONST(AST__NGDIN)
      else TRY_CONST(AST__PATIN)
      else TRY_CONST(AST__SISIN)
      else TRY_CONST(AST__SSPIN)
      else TRY_CONST(AST__UINER)
      else TRY_CONST(AST__UK1ER)
      else TRY_CONST(AST__COMIN)
      else TRY_CONST(AST__CONIN)
      else TRY_CONST(AST__DUVAR)
      else TRY_CONST(AST__INNTF)
      else TRY_CONST(AST__MIOPA)
      else TRY_CONST(AST__MIOPR)
      else TRY_CONST(AST__MISVN)
      else TRY_CONST(AST__MLPAR)
      else TRY_CONST(AST__MRPAR)
      else TRY_CONST(AST__NORHS)
      else TRY_CONST(AST__UDVOF)
      else TRY_CONST(AST__VARIN)
      else TRY_CONST(AST__WRNFA)
      else TRY_CONST(AST__BADUN)
      else TRY_CONST(AST__NORSF)
      else TRY_CONST(AST__NOSOR)
      else TRY_CONST(AST__SPCIN)
      else TRY_CONST(AST__XMLNM)
      else TRY_CONST(AST__XMLCM)
      else TRY_CONST(AST__XMLPT)
      else TRY_CONST(AST__XMLIT)
      else TRY_CONST(AST__XMLWF)
   }
   if ( ! success ) printf( "no such constant %s\n", ident );
   (*env)->ReleaseStringUTFChars( env, jIdent, ident );
   if ( ! success ) {
      jniastThrowIllegalArgumentException( env, "No such constant" );
   }
   return result;
}
