/*
*+
*  Name:
*     err_jniast.c

*  Purpose:
*     Error message module for AST called from JNI.

*  Language:
*     ANSI C.

*  Description:
*     This module provides the astPutErr function which is called by
*     routines in the AST library when an error is detected.
*     It simply concatenates any messages registered by this routine
*     and provides functions by which the error can be retrieved.
*
*     Note that this, like the error-handling mechanism of the AST C 
*     library itself, assumes that only one thread is executing AST
*     code at any one time.  Care should therefore be taken with 
*     synchronisation of the methods which call astPutErr.

*  Authors:
*     MBT: Mark Taylor (Starlink)

*  History:
*     18-SEP-2001 (MBT):
*        Original version.
*-
*/

/* Header files. */
#include "err_jniast.h"

/* Constants. */
#define BUFLENG 1024

/* Static variables. */
static char buffer[ BUFLENG ];
static int msgleng = 0;


/* Public function. */
void astPutErr_( int status, const char *message ) {
/*
*  Name:
*     astPutErr

*  Purpose:
*     Deliver an error message.

*  Type:
*     Protected function.

*  Synopsis:
*     #include "err.h"
*     void astPutErr( int status, const char *message )

*  Description:
*     This function registers an error message by storing it in a buffer,
*     appended to any others which have been written since the last call
*     to jniastClearErrMsg().  The current value of the buffer can be
*     got by calling jniastGetErrMsg().  The buffer is of fixed length;
*     any messages too long to fit in it are silently discarded.

*  Parameters:
*     status
*        The error status value.
*     message
*        A pointer to a null-terminated character string containing
*        the error message to be delivered. This should not contain
*        newline characters.
*-
*/
   if ( msgleng < BUFLENG - 2 ) {
      if ( msgleng > 0 ) {
         buffer[ msgleng++ ] = '\n';
      }
      while ( msgleng < BUFLENG - 1 && *message != '\0' ) {
         buffer[ msgleng++ ] = *(message++);
      }
      buffer[ msgleng ] = '\0';
   }
}


/* Package functions. */
void jniastClearErrMsg() {
/*
*+
*  Name:
*     jniastClearErrMsg

*  Purpose:
*     Reset the contents of the JNI/AST error message buffer.

*  Description:
*     This routine should be called at the start of a new AST 'error
*     context', i.e. before a sequence of AST calls is made, to ensure
*     that there are no pending error messages.
*-
*/
   *buffer = '\0';
   msgleng = 0;
}

const char *jniastGetErrMsg() {
/*
*+
*  Name:
*     jniastGetErrMsg

*  Purpose:
*     Retrieve the contents of the JNI/AST error message buffer.

*  Description:
*     This routine returns a pointer to a string giving a concatenation
*     of all error messages logged by AST since the last call to 
*     jniastClearErrMsg().

*  Return value:
*     A pointer to a static buffer containing the error message text.
*     Messages generated by separate calls from AST are separated
*     by newline characters.  The string is terminated by a zero,
*     but not by an additional newline.
*-
*/
   return buffer;
}

/* $Id$ */
