#!/bin/sh
#  Note JVM seems to depend on /bin/sh signature, do not remove.

#  Name: 
#     mk

#  Purpose:
#     Wrapper script for running JNI build system. Replaces mk script from old
#     build system. Really depends on local directory containing a starconf'd
#     system  in the "dist" state (this has at least a configure script and
#     Makefile.in). If this isn't true will attempt to run "bootstrap" first.

#  Authors:
#     PWD: Peter W. Draper (Starlink, Durham University)
#     {enter_new_authors_here}
#
#  History:
#     22-JUL-2004 (PWD):
#        Original version.
#     {enter_further_changes_here}
#-

if test -f "configure"; then
    ./configure --prefix=${TARGET_LIB}
    make
else
    echo "Failed to locate build system"
endif



#  End of script.
