#!/bin/sh
#  Note JVM seems to depend on /bin/sh signature, do not remove.

#  Name: 
#     mk

#  Purpose:
#     Wrapper script for running JNI build system. Replaces mk script from old
#     build system. Really depends on local directory containing a starconf'd
#     system  in the "dist" state (this has at least a configure script and
#     Makefile.in).
#
#     The location of the AST & SLA libraries is determined by the STARLINK
#     environment variable (defaults to what was baked into the configure
#     script when bootstrap was last run, should really make that /star) and
#     and where to install the library is determined by TARGET_LIB (again this
#     defaults to the standard place for installing libraries baked into the
#     configure script).

#  Authors:
#     PWD: Peter W. Draper (Starlink, Durham University)
#     {enter_new_authors_here}
#
#  History:
#     22-JUL-2004 (PWD):
#        Original version.
#     {enter_further_changes_here}
#-

#  Never want INSTALL preset.
export INSTALL
unset INSTALL

#  Look for configure script, if not found give up.
if ! test -f "configure"; then
    echo "Failed to locate a configure script"
    exit 1
fi

#  Run configure, looking for standard libraries in $STARLINK, or the
#  configure script default position.
if test -z "$STARLINK"; then
   echo "./configure"
   ./configure
else
   echo "./configure --prefix=${STARLINK}"
   ./configure --prefix=${STARLINK}
fi

#  Create the shareable dl-loadable library.
echo "make"
make

#  Install the library in TARGET_LIB (use libdir to avoid getting an extra
#  /lib on prefix) or the standard place.
if test -z "$TARGET_LIB"; then
   echo "make install"
   make install
else
   echo "make libdir=${TARGET_LIB} install"
   make prefix=${TARGET_LIB} libdir=${TARGET_LIB} install
fi

exit
