#!/bin/sh

#+
#  Name:
#     treeview

#  Purpose:
#     Invokes the Treeview application on Unix

#  Description:
#     This shell script invokes the Treeview application.
#     It locates a JVM and invokes 'java -jar' on the treeview.jar jar file,
#     also setting some properties which Treeview uses to work out the
#     positions of auxiliary files and so on.
#
#     However, the Treeview application itself will do its best to guess
#     values for these properties if they have not been defined when it 
#     wakes up.  Therefore it is usually possible to bypass this script
#     if desired (for instance on non-Unix operating systems) by 
#     simply invoking 'java -jar treeview.jar'.  If native libraries are
#     being used, the system should be set up so that the directory
#     containing them is on the java.library.path.  On Unix this would be
#     done by putting wherever/java/lib on LD_LIBRARY_PATH.

#  Authors:
#     MBT: Mark Taylor (Starlink)
#-

#  Find where this script is located.

if test -z "$TREEVIEW_DIR"; then
   TREEVIEW_DIR=`dirname $0`
fi
starjava_bin_dir="${TREEVIEW_DIR}"
starjava_dir="$starjava_bin_dir/.."

#  Locate referenced server dirs.

if test -z "$SPLAT_DIR"; then
   SPLAT_DIR="$starjava_bin_dir/splat"
   export SPLAT_DIR
fi
if test -z "$SOG_DIR"; then
   SOG_DIR="$starjava_bin_dir/sog"
   export SOG_DIR
fi

#  Locate the application jar file.  This is relative to this script.

appjar="$starjava_dir/lib/treeview/treeview.jar"
if test ! -f "$appjar"; then
   echo "Failed to locate the TREEVIEW jar file.  Please define TREEVIEW_DIR"
fi

#  Locate the java startup script.

starjava="$starjava_bin_dir/starjava"
if test ! -f "$starjava"; then
   echo "Failed to locate the 'starjava' script.  Trying with java on path"
   starjava="java"
fi

#  Locate demo data.

demodir="$starjava_dir/etc/treeview/demo"

#  Make sure that we get the installed shareable libraries.
if test -z "$LD_LIBRARY_PATH"; then
   LD_LIBRARY_PATH="$starjava_dir/lib"
else
   LD_LIBRARY_PATH="$starjava_dir/lib:${LD_LIBRARY_PATH}"
fi
export LD_LIBRARY_PATH

#  Run Treeview.

$starjava \
   -Duk.ac.starlink.treeview.cmdname="treeview" \
   -Duk.ac.starlink.treeview.demodir="$demodir" \
   -Duk.ac.starlink.treeview.sogdir="$SOG_DIR" \
   -Duk.ac.starlink.treeview.splatdir="$SPLAT_DIR" \
   -enableassertions \
   -jar $appjar $*
  
