# Makefile
#
# Copyright 2000 Association for Universities for Research in Astronomy, Inc.,
# Observatory Control System, Gemini Telescopes Project.
#
# $Id: Makefile,v 1.4 2002/08/08 22:40:23 gillies Exp $
#

# Source files to compile
SOURCES = \
	CanvasFigure.java \
	CanvasFigureEvent.java \
	CanvasFigureListener.java \
	CanvasFigureListenerManager.java \
	CanvasFigureListenerAdapter.java \
	CanvasGraphics.java \
	CanvasFigureGroup.java \
	SelectedAreaListener.java \


# Java package name
PACKAGE_DIR = jsky/graphics

# Path to top level dir
TOP = ../../..

# include master makefile
include $(TOP)/conf/master.mk


# tests
test: 
